version: '2.2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./data/src/migrations:/docker-entrypoint-initdb.d
      - '/var/run/docker.sock:/var/run/docker.sock'
